#pragma once
#ifndef __TILE_TYPE__
#define __TILE_TYPE__

enum TileType 
{
	FLOOR,
	RIGHT_DOOR,
	LEFT_DOOR,
	TOP_LEFT_OUT,
	TOP_LEFT_IN,
	LEFT_WALL,
	BOTTOM_LEFT_OUT,
	BOTTOM_LEFT_IN,
	BOTTOM_WALL,
	BOTTOM_RIGHT_IN,
	BOTTOM_RIGHT_OUT,
	RIGHT_WALL,
	TOP_RIGHT_IN,
	TOP_RIGHT_OUT,
	TOP_WALL,
	NUM_OF_TILE_TYPES
};
#endif 